config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  
  resources :products do
    collection do
      get 'show_add_to_cart'
    end
  end

  post "checkout/create", to: "checkout#create"
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"

  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, presence: true

  has_one_attached :product_image

  def to_s
    name
  end



  # transform shopping cart products into an array of line items
  def to_builder
    Jbuilder.new do |product|
      product.price stripe_price_id
      product.quantity 1
    end
  end

  # create stripe product and assign to this product
  after_create do
    product = Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product, unit_amount: self.price, currency: self.currency)
    update(stripe_product_id: product.id, stripe_price_id: price.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :initialize_session
  before_action :load_cart

  private

  def initialize_session
    session[:cart] ||= [] # empty cart = empty array
  end

  def load_cart
    @cart = Product.where(id: session[:cart])
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def create
    line_items = []

    customer = Stripe::Customer.create(
      email: current_user.email,
      description: "Customer id: #{current_user.id}"
    )

    if params[:single_product]
      product = Product.find(params[:id])
      line_items << {
        price_data: {
          currency: product.currency,
          product_data: {
            name: product.name,
            description: product.description,
          },
          unit_amount: product.price,
        },
        quantity: 1,
      }
    else

      if @cart.pluck(:currency).uniq.length > 1
        redirect_to products_path, alert: "You cannot select products with different currencies in one checkout."
      end

      line_items = @cart.map do |item|
        {
          price_data: {
            currency: item.currency,
            product_data: {
              name: item.name,
              description: item.description
            },
            unit_amount: item.price,
          },
          quantity: 1
        }
      end
    end

    @session = Stripe::Checkout::Session.create(
      customer: customer.id,
      payment_method_types: ['card'],
      line_items: line_items,
      allow_promotion_codes: true,
      mode: 'payment',
      success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: cancel_url
    )
    redirect_to @session.url, allow_other_host: true

  end

  def success
    if params[:session_id].present?
      # session.delete(:cart)
      session[:cart] = [] # empty cart = empty array
      @session_with_expand = Stripe::Checkout::Session.retrieve({ id: params[:session_id], expand: ["line_items"]})
      @session_with_expand.line_items.data.each do |line_item|
        product = Product.find_by(stripe_product_id: line_item.price.product)
      end
    else
      redirect_to cancel_url, alert: "No info to display"
    end
  end

  def cancel
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show update destroy ]

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :price_cents, :currency, :description, :product_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkout/cancel.html.erb
<h1>Cancelled</h1>

app/views/checkout/success.html.erb
<h1>Success</h1>

Checkout status: <%= @session_with_expand.payment_status %>
<br>
Amount paid:
<%= @session_with_expand.amount_total/100.to_f %>
<%= @session_with_expand.currency %>

<% @session_with_expand.line_items.data.each do |line_item| %>
  <% product = Product.find_by(stripe_product_id: line_item.price.product) %>
  <br>
  <%= product.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <center>
        <h1>Stripe eCommerce app </h1>
    </center>

    <% if user_signed_in? %>
      <!-- Display user information or sign out link -->
      Welcome <%= current_user.email %>!
      <br>
      <div class="row">
        <div class="col g-4" >
          <%= link_to "All Products", products_path, style: 'width: 205px; height: 40px;', class: 'btn btn-dark'%>
        </div>
        <div class="col g-4" >
          <%= link_to 'Cart',  show_add_to_cart_products_path, style: 'width: 100px; height: 40px;', class:"btn btn-dark" %>
        </div>
        <div class="col g-4" >
        <%= link_to 'New Product', new_product_path, style: 'width: 150px; height: 40px;', class: 'btn btn-dark' %>
      </div>
      <div>
      <div style="text-align: left; padding-left: 1200px;">
        <%= link_to 'Sign out',  destroy_user_session_path, method: :delete, width: '70px; height: 30px;', class: 'btn btn-danger' %>
      </div>
    <hr>
    <% end %>

    <div>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
   <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<center>
 <%= form_with(model: product) do |form| %>
    <% if product && product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :currency %>
      <%= form.select :currency, ["usd", "inr", "eur", "pln", "uah"] %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label 'Please attached image '%>
        <div class="col">
          <%= form.file_field :product_image %>
        </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</center>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<center>
  <div class="card mb-3" style="max-width: 640px;">
    <% @products.each do |product| %>
      <div class="row g-0">
        <div class="col-md-4 d-flex align-items-center justify-content-center">
          <% if product&.product_image&.attached? %>
            <%= image_tag product.product_image, height: 200, width: 150, class: 'img-fluid' %>
          <% end %>
          <div class="button-group" style="display: flex; flex-direction: column; align-items: center; gap: 10px; padding-top: 10px;">
            <%= link_to 'Show', product, class: 'btn btn-dark' %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-dark' %>
          </div>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text">Name: <%= product.name %></p>
            <p class="card-text">Currency: <%= product.currency %></p>
            <p class="card-text">Price: <%= product.price %></p>
            <p class="card-text">Sales: <%= product.price_cents %></p>
            <p class="card-text">Description: <%= product.description %></p>
            <p class="card-text">
              <% if @cart.present? && @cart.include?(product) %>
                <%= button_to "Remove from cart", remove_from_cart_path(product), method: :delete, class: 'btn btn-warning' %>
              <% else %>
                <%= button_to "Add to cart", add_to_cart_path(product), class: 'btn btn-success' %>
              <% end %>
            </p>
            <p class="card-text">
            <%= button_to "Buy now!", checkout_create_path(price_id: product.stripe_price_id), remote: true, data: { turbo: false }, params: { id: product.id, single_product: true}, class: 'btn btn-success' %>
            </p>
        </div>
      </div>
      <% end %>
      <br>
  </div>
</center>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<center>
 <div class="login-box">
    <p>
      <strong>Name:</strong>
      <%= @product&.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product&.price %>$
    </p>

    <p>
    <% if @product&.product_image&.attached? %>
    <%= image_tag @product.product_image, height:150, width:150 %>
    <% end %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-dark' %> |
    <%= link_to "Destroy", products_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: 'btn btn-dark' %></li>
    <br>
    <br>
    <%= link_to "Back", products_path, class: 'btn btn-dark' %>
  </div>
</center>

app/views/products/show_add_to_cart.html.erb
<div class="shopping-cart-box">
  <h1>Shopping cart</h1>
  <% if @cart.present? %>
    <% @cart.each do |product| %>
      <%= product.name %><br>
    <% end %>
    <%= button_to "Buy now!", checkout_create_path, remote: true, data: { disable_with: "Validating..." }, class: 'btn btn-success' %>

  <% else %>
    <p>Your cart is empty</p>
  <% end %>
</div>
<br>
<%= link_to "Back", products_path, class: 'btn btn-dark' %>